AllCops:
  Excludes:
    - Rakefile
    - vendor/**
    - bin/**

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false
